# Generated by Django 3.0.7 on 2020-06-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomNo', models.CharField(max_length=10)),
                ('roomName', models.CharField(max_length=50)),
                ('roomAddr', models.CharField(max_length=256)),
                ('roomSts', models.CharField(max_length=1)),
                ('roomLevel', models.CharField(max_length=10)),
                ('roomMedia', models.CharField(max_length=20)),
            ],
        ),
    ]
